# Generated by Django 5.1 on 2024-09-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_product_price_basket_product_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='text',
            new_name='desc',
        ),
    ]
