# Generated by Django 5.1 on 2024-09-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_rename_text_product_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='basket',
        ),
    ]
