# Generated by Django 5.1 on 2024-09-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basket',
            field=models.ManyToManyField(to='shopping.basket'),
        ),
    ]
