# Generated by Django 5.1 on 2024-09-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_remove_product_basket_product_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.basket'),
        ),
    ]
