# Generated by Django 5.1 on 2024-09-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_alter_product_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='basket',
        ),
        migrations.AddField(
            model_name='product',
            name='basket',
            field=models.ManyToManyField(to='shopping.basket'),
        ),
    ]
