# Generated by Django 5.1 on 2024-09-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_remove_product_basket_product_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='basket',
            field=models.ManyToManyField(default=1, to='shopping.basket'),
        ),
    ]
