# Generated by Django 5.1 on 2024-09-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_alter_product_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='basket',
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(to='shopping.product'),
        ),
    ]
