# Generated by Django 5.1 on 2024-09-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_remove_basket_products_basketitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(to='shopping.product'),
        ),
        migrations.DeleteModel(
            name='BasketItems',
        ),
    ]
